# Generated by Django 3.2.7 on 2022-01-23 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=100)),
                ('elocation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('efirst_name', models.CharField(max_length=100)),
                ('elast_name', models.CharField(max_length=100)),
                ('esal', models.FloatField()),
                ('ebonus', models.IntegerField(default=0)),
                ('ephone', models.IntegerField(default=0)),
                ('ehire_date', models.DateField()),
                ('edept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.department')),
                ('erole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.role')),
            ],
        ),
    ]
