# Generated by Django 3.2.7 on 2022-01-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='elocation',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
