# Generated by Django 3.2.7 on 2022-01-30 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_employee_elocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='edept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='erole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.role'),
        ),
    ]
